package cache

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

type HashMetadata struct {
	GopherVersion string    `json:"gopher_version"`
	GoVersion     string    `json:"golang_version"`
	Hashes        HashFiles `json:"hashes"`
}

func Valid(gopherfile string, directory string, goBin string) (bool, error) {
	/* TODO: Implement all this
	Things that need to be true to be valid.
		- directory/hash exists and is valid json of HashFileContent
		- directory/hash == HashMetadata {
				GopherVersion: TODO: Figure if we need this now or can add it later.
				GoVersion: > go version (Don't need to hash)
				Hashes: CalculateFileHashes(...),
			}
	*/
	// expectedHashMetadata := ReadHashFile(...)
	// TODO: READ FROM A FILE and have compile write it
	expectedHashMetadata := HashMetadata{}

	hashes, err := CalculateFileHashes(gopherfile, directory)
	if err != nil {
		return false, err
	}

	existingHashMetadata := HashMetadata{
		Hashes:        hashes,
		GopherVersion: "Initial dev of this feature",
		// TODO: Run go version to confirm that its the same
		// TODO: GoVersion: "..."
	}
	return existingHashMetadata == expectedHashMetadata, nil
}

type HashFiles struct {
	GopherFile string `json:"gopherfile"`
	TargetFile string `json:"targets.go"`
	Main       string `json:"main.go"`
	GoMod      string `json:"go.mod"`
	GoSum      string `json:"go.sum"`
}

func CalculateFileHashes(gopherfile string, directory string) (HashFiles, error) {
	var hashes HashFiles
	var err error

	hashes.GopherFile, err = HashFile(gopherfile)
	if err != nil {
		return hashes, fmt.Errorf("parsing: %s: %w", gopherfile, err)
	}

	// NOTE: These are generated by us, so if they are missing
	//       We just leave them empty
	hashes.TargetFile, err = HashFile(filepath.Join(directory, "targets.go"))
	if err != nil {
		slog.Debug("could not open targets.go", "err", err)
	}

	hashes.Main, err = HashFile(filepath.Join(directory, "main.go"))
	if err != nil {
		slog.Debug("could not open main.go", "err", err)
	}

	// TODO: These are not made currently so uncomment when they are
	hashes.GoMod, err = HashFile(filepath.Join(directory, "go.mod"))
	if err != nil {
		slog.Debug("could not open go.mod", "err", err)
	}

	hashes.GoSum, err = HashFile(filepath.Join(directory, "go.sum"))
	if err != nil {
		slog.Debug("could not open go.sum", "err", err)
	}
	return hashes, nil
}
func HashFile(filepath string) (string, error) {
	content, err := os.ReadFile(filepath)
	if err != nil {
		return "", err
	}
	return Hash(string(content)), nil
}

func Hash(content string) string {
	// TODO: Implement a better hash function
	return content
}
