#!/bin/bash
cat > report/stdlib.go << 'EOF'
// Code generated by go generate; DO NOT EDIT.
package report
var stdlibPackages = map[string]string{
EOF

declare -A seen

go list std | grep -v internal | grep -v vendor | grep -v 'cmd/' | while read -r pkg; do
    if [ -n "$pkg" ]; then
        base=$(basename "$pkg")
        if [ -z "${seen[$base]}" ]; then
            echo "    \"$base\": \"$pkg\"," >> report/stdlib.go
            seen[$base]=1
        else
            echo "    // \"$base\": \"$pkg\", // duplicate key" >> report/stdlib.go
        fi
    fi
done

echo "}" >> report/stdlib.go

gofmt -w report/stdlib.go
